# Generated by Django 5.1.2 on 2024-11-04 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('formato_compra', models.CharField(help_text='ej: Cajón/Saco', max_length=255)),
                ('cantidad_por_formato', models.FloatField(help_text='17kg/10und')),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('UNIDAD', 'Unidades')], default='KG', max_length=10)),
                ('stock_actual', models.FloatField(help_text='en kg/und')),
                ('precio_venta', models.FloatField(help_text='por kg/und')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='CompraStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_formatos', models.IntegerField()),
                ('total_agregado', models.FloatField(help_text='en kg/und')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('UNIDAD', 'Unidades')], default='KG', max_length=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.producto')),
            ],
            options={
                'verbose_name': 'Compra de Stock',
                'verbose_name_plural': 'Compras de Stock',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador')], default='cliente', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.FloatField(help_text='en kg/und')),
                ('precio_unitario', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('UNIDAD', 'Unidades')], default='KG', max_length=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
