# Generated by Django 5.1.2 on 2024-10-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
