# Generated by Django 5.1.2 on 2024-10-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_destacado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='destacado',
        ),
    ]
