# Generated by Django 5.1.2 on 2024-10-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_tarea_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'permissions': [('editor_access', 'Permiso para agregar, editar y eliminar tareas')]},
        ),
    ]
