# Generated by Django 5.1.2 on 2024-11-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='disponible',
        ),
        migrations.AddField(
            model_name='libro',
            name='cantidad_disponible',
            field=models.IntegerField(default=1),
        ),
    ]
