# Generated by Django 5.1.2 on 2024-11-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_libro_disponible_libro_cantidad_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad_total',
            field=models.IntegerField(default=1),
        ),
    ]
