# Generated by Django 5.1.2 on 2024-11-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_libro_cantidad_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
